#Seed Settings
[seeds]
	#The rate at which seeds drop from leaves.
	# Default: 1.0
	# Range: 0.0 ~ 64.0
	leavesSeedDropRate = 1.0
	#The rate at which seeds voluntarily drop from branches
	# Default: 0.01
	# Range: 0.0 ~ 1.0
	voluntarySeedDropRate = 0.01
	#The rate at which seeds voluntarily plant themselves in their ideal biomes
	# Default: 0.1666666716337204
	# Range: 0.0 ~ 1.0
	seedPlantRate = 0.1666666716337204
	#Ticks before a seed in the world attempts to plant itself or despawn. 1200 = 1 minute
	# Default: 1200
	# Range: 0 ~ 6000
	seedTimeToLive = 1200
	#If enabled then seeds will only voluntarily plant themselves in forest-like biomes.
	seedOnlyForest = true
	#The minimum forestness that non-forest-like biomes can have. 0 = is not at all a forest, 1 = may as well be a forest. Can be fractional.
	# Default: 0.0
	# Range: 0.0 ~ 1.0
	seedMinForestness = 0.0

#Tree Settings
[trees]
	#Factor that multiplies the rate at which trees grow. Use at own risk
	# Default: 0.5
	# Range: 0.0 ~ 16.0
	treeGrowthMultiplier = 0.5
	#Factor that multiplies the wood returned from harvesting a tree.  You cheat.
	# Default: 1.0
	# Range: 0.0 ~ 128.0
	treeHarvestMultiplier = 1.0
	#Maximum harvesting hardness that can be calculated. Regardless of tree thickness.
	# Default: 20.0
	# Range: 1.0 ~ 200.0
	maxTreeHardness = 20.0
	#A multiplier of tree hardness. Higher values make trees slower to chop, lower values makes them faster to chop.
	# Default: 1.0
	# Range: 0.0078125 ~ 32.0
	treeHardnessMultiplier = 1.0
	#If enabled then sticks will be dropped for partial logs
	dropSticks = true
	#Scales the growth for the environment.  0.5f is nominal. 0.0 trees only grow in their native biome. 1.0 trees grow anywhere like they are in their native biome
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	scaleBiomeGrowthRate = 0.5
	#The chance of a tree on depleted soil to die. 1/256(~0.004) averages to about 1 death every 16 minecraft days
	# Default: 0.0
	# Range: 0.0 ~ 1.0
	diseaseChance = 0.0
	#The maximum radius of a branch that is allowed to postRot away. 8 = Full block size. 24 = Full 3x3 thick size. Set to 0 to prevent rotting
	# Default: 7
	# Range: 0 ~ 24
	maxBranchRotRadius = 7
	#How much harder it is to destroy a rooty block compared to its non-rooty state
	# Default: 40.0
	# Range: 0.0 ~ 128.0
	rootyBlockHardnessMultiplier = 40.0
	#Options for how oak trees generate in swamps. ROOTED: Swamp oak trees will generate on shallow water with mangrove-like roots. SUNK: Swamp oak trees will generate on shallow water one block under the surface. DISABLED: Swamp oaks will not generate on water.
	#Allowed Values: ROOTED, SUNK, DISABLED
	swampOaksInWater = "ROOTED"
	#The amount of growth pulses to send when bone meal is applied to a tree. Warning: setting values higher than 64 is not recommended other than for testing purposes. 
	# Default: 1
	# Range: 1 ~ 512
	boneMealGrowthPulses = 1

#Interaction Settings
[interaction]
	#If enabled all leaves will be passable. If the Passable Foliage mod is installed this config is overridden
	isLeavesPassable = false
	#If enabled player movement on leaves will not be enhanced
	vanillaLeavesCollision = false
	#If enabled then thinner branches can be climbed
	enableBranchClimbing = true
	#If enabled players receive reduced fall damage on leaves at the expense of the block(s) destruction
	enableCanopyCrash = true
	#Damage dealt to the axe item when cutting a tree down. VANILLA: Standard 1 Damage. THICKNESS: By Branch/Trunk Thickness. VOLUME: By Tree Volume.
	#Allowed Values: VANILLA, THICKNESS, VOLUME
	axeDamageMode = "THICKNESS"
	#If enabled then trees will fall over when harvested
	enableFallingTrees = true
	#If enabled then trees will harm living entities when falling
	enableFallingTreeDamage = true
	#Multiplier for damage incurred by a falling tree
	# Default: 1.0
	# Range: 0.0 ~ 100.0
	fallingTreeDamageMultiplier = 1.0
	#If enabled the Dirt Bucket will place a dirt block on right-click
	dirtBucketPlacesDirt = true
	#If enabled then improperly broken trees(not by an entity) will still drop wood.
	sloppyBreakDrops = false
	#The minimum radius a branch must have before its able to be stripped. 8 = Full block size. Set to 0 to disable stripping trees
	# Default: 6
	# Range: 0 ~ 24
	minRadiusForStrip = 6
	#If enabled, stripping a branch will decrease its radius by one
	enableStripRadiusReduction = true
	#Sets the default for whether or not fruit growing from dynamic trees can be bone-mealed. Note that this is a default; it can be overridden by the individual fruit.
	canBoneMealFruit = false
	#Sets the default for whether or not pods growing from dynamic trees can be bone-mealed. Note that this is a default; it can be overridden by the individual pod.
	canBoneMealPods = true
	#If enabled, dynamic sapling blocks will drop their seed when broken.
	dynamicSaplingDrops = true

#World Generation Settings
[world]
	#Randomly generate podzol under select trees like spruce.
	generatePodzol = true
	#World Generation produces Dynamic Trees instead of Vanilla trees.
	worldGen = true
	#Blacklist of dimension registry names for disabling Dynamic Tree worldgen
	dimensionsBlacklist = []

#Debug Settings
[debug]
	#Enable to mark tree spawn locations with concrete circles.
	debug = false
