#Client settings
[client]
	#When enabled makes the mobs look more gender neutral (default: false)
	genderNeutral = false
	#When enabled effect tooltips on edible items will be hidden (default: false)
	hideFoodEffectTooltips = false
